### ISSUE TITLE
meta: remaining MIDI-CI tasks

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/ktmidi#56]
Here is the list of missing features in `dev.atsushieno.ktmidi.ci` package:

- [x] property message chunking. It would result in separation of `Message` and the actual message packets in SysEx message units
- [ ] support for zlib+Mcoded7 (we need zlib implementation for KMP) -> works on desktop now
- [x] apply property body binary conversion based on `mutualEncoding`
- ~initiator: ChannelList~ app developer should provide it
- ~initiator: Schema~ app developer should provide it
- [x] ASCII validation of strings (product instance ID)
- [x] initiator: Profile Details Inquiry
- [x] initiator: Property subscription and subscription management
- [x] move logging facility from midi-ci-tool (app) to ktmidi (library) module
- [x] responder: overall UI
- [x] responder: partial property update by RFC6901 (needs to parse the expressions and apply patching updates)
- [x] initiator: partial property update by RFC6901 for subscription updates
- [x] overall message buffer size verification
- [x] Process Inquiry
- [x] MIDI message report implementation (entrypoints are already implemented in ktmidi-ci)
- [x] probably define `Muid` type that only contains an `Int` value but ensures that its data content is 28 bit and supports appropriate conversion -> so far it is visible as 28bit on UI
- [x] save/load local configuration
- [x] initiator UI: there should be device info configuration (currently it is only for  responder)
- [x] overall MUID validation
- [x] take out muid from SavedSettings (it must be always uniquely created)
- [x] end subscription
- [x] support "group" in Message and everywhere applicable
- [ ] timeout manager (adds some threading complication)
- [ ] app startup/terminate lifecycle support (we can kinda skip that; the specification anticipates InvalidateMUID may not be sent)
- [x] property pagination

**Comment by atsushieno** [comment]
For zlib compression, it would be best that we wait for ktor-utils 3.0.0 release (which contains `DeflateEncoder`).

**Comment by atsushieno** [comment]
For MIDI Message Report we would need to make some fundamental changes to `Midi1Machine` and `Midi2Machine` to preserve assigned state (make them tristates) and provide "catalog" on which CCs, RPNs, NRPNS, and per-note of those are "supported".

**Comment by atsushieno** [comment]
Group support is implemented, but we need MIDI 2.0 I/O support at device level in ktmidi in the first place. Currently it is supported only in AlsaMidiAccess virtual I/O.

**Comment by atsushieno** [comment]
Those remaining issues are split into individual tasks. Closing this long-running issue.
